meta_product_name: "Penser c'est chouette"
meta_title: "Penser c'est chouette - Le réseau social de la dialectique: Ecologie, Politique, Economie, Numérique"
meta_description: "Le réseau social de la dialectique: Ecologie, Politique, Economie, Numérique, Humanités"
meta_image: "logopcc.png" # should exist in `app/assets/images/`
  # required for Twitter Cards
