meta_product_name: "Penser c'est chouette"
meta_title: "Penser c'est chouette - 1er réseau social d'échange d'informations et de débat: Ecologie, Politique, Economie, Numérique"
meta_description: "1er réseau social d'échange d'informations et de débat: Ecologie, Politique, Economie, Numérique"
meta_image: "logopcc.png" # should exist in `app/assets/images/`
  # required for Twitter Cards
